export const poets = [
    {
        id: 1,
        name: "Rabindranath Tagore",
        image: "https://i.ibb.co/mCGXSQR/1024px-Rabindranath-Tagore-5c50f0a946e0fb0001c0dd28.jpg",
        birthplace: "Jorasanko Thakurbari, Kolkata, India",
        description: "Rabindranath Tagore FRAS was a Bengali polymath who worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1861,
        famouspoem: "Gitanjali",
    },
    {
        id: 2,
        name: "Kazi Nazrul Islam",
        image: "https://i.ibb.co/rfVKfYy/Islam-Kazi-Nazrul.jpg",
        birthplace: "Churulia, India",
        description: "Kazi Nazrul Islam was a Bengali poet, writer, musician, and is the national poet of Bangladesh. Nazrul is regarded as one of the greatest poets in Bengali literature.worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1899,      
        famouspoem: "Bidrohi",

    },
    {
        id: 3,
        name: "Michael Madhusudan Dutt",
        image: "https://i.ibb.co/gF4tT48/4ada4-f093b6c112-long.jpg",
        birthplace: "Jessore District",
        description: "Michael Madhusudan Dutt was a Bengali poet and playwright. He is considered one of the pioneers of Bengali literature.worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1824,
        famouspoem: "Kapotakkho Nod",
    },
    {
        id: 4,
        name: "Sufia Kamal",
        image: "https://i.ibb.co/8dWLmLH/images.jpg",
        birthplace: "Tahare Pore Mone",
        description: "Begum Sufia Kamal was a Bangladeshi poet, feminist leader, and political activist. She took part in the Bengali nationalist movement of the 1950s and civil society leader in independent Bangladesh. She led feminist activism and was a president of Bangladesh Mahila Parishad.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1911,
        famouspoem: "Kapotakkho Nod",
    },
    {
        id: 5,
        name: "Edgar Allen Poe",
        image: "https://i.ibb.co/Gvs8JZy/Edgar-Allan-Poe-1.webp",
        birthplace: "Boston",
        description: "Edgar Allan Poe was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1809,
        famouspoem: "The Raven",
    },
    {
        id: 6,
        name: "William Shakespeare",
        image: "https://i.ibb.co/82ygx6Y/shakespeare.jpg",
        birthplace: "Stratford-upon-Avon, England",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1564,
        famouspoem: "Sonnet XVIII",
    },
    {
        id: 7,
        name: "Maya Angelou",
        image: "https://i.ibb.co/ZY83RwR/3503.jpg",
        birthplace: "St. Louis",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1928,
        famouspoem: "On the Pulse of Morning",
    },
    {
        id: 8,
        name: "Shel Silverstein",
        image: "https://i.ibb.co/w0w6Kzz/Shel-Silverstein.webp",
        birthplace: "Chicago",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1930,
        famouspoem: "Where the Sidewalk Ends",
    },
    {
        id: 9,
        name: "Robert Frost",
        image: "https://i.ibb.co/0KH59Mf/Robert-Frost-1910s.jpg",
        birthplace: "San Francisco",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1874,
        famouspoem: "The Road Not Taken",
    },
    {
        id: 10,
        image: "https://i.ibb.co/HNjfq8D/neruda-13228-portrait-medium.jpg",
        name: "Pablo Neruda",
        birthplace: "Parral, Chile",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1904,
        famouspoem: "I Do Not Love You Except Because I Love You",
    },
    {
        id: 11,
        name: "E. E. Cummings",
        image: "https://i.ibb.co/JBZb95t/140303-r24673.webp",
        birthplace: "Cambridge, Massachusetts",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1894,
        famouspoem: "i carry your heart with me",
    },
    {
        id: 12,
        name: "John Keats",
        image: "https://i.ibb.co/vdDX057/images-1.jpg",
        birthplace: "London",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1795,
        famouspoem: "A Thing of Beauty",
    },
    {
        id: 13,
        name: "Jalal al-Din Rumi",
        image: "https://i.ibb.co/MhxpG2K/images-2.jpg",
        birthplace: "Khorasan present-day Afghanistan",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1207,
        famouspoem: "Masnavi-ye Ma’navi",
    },
    {
        id: 14,
        name: 'Albert Einstein',
        image: 'https://i.ibb.co/VvFcmM1/2da94bdb2f624acd59235f74dc4d3aee.jpg',
        birthplace: 'German',
        description: 'Albert Einstein was a German-born theoretical physicist, widely acknowledged to be one of the greatest and most influential physicists of all time. Einstein is best known for developing the theory of relativity, but he also made important contributions to the development of the theory of quantum mechanics.',
        birthyear: 1879-1955,


    },
    {
        id: 15,
        name: 'Galileo Galilei',
        image: 'https://i.ibb.co/jRbdLQD/Justus-Sustermans-Portrait-of-Galileo-Galilei-1636.jpg',
        birthplace: 'Pisa, Italy',
        description: 'The father of modern science, Galileo discovered the first moons ever known to orbit another planet and that the Milky Way is .. Born in Pisa, Italy in 1564, Galileo is called as the father of modern science because of his discoveries in astronomy and Galileo discovered the first moons ever known to orbit another planet and that the Milky Way i.Galileo discovered the first moons ever known to orbit another planet and that the Milky Way i ',
        birthyear: 1564-1642,


    },
    {
        id: 16,
        name: 'Sir Isaac Newton',
        image: 'https://i.ibb.co/2YcNVNg/gettyimages-113494597-612x612.jpg',
        birthplace: '',
        description: 'Sir Isaac Newton PRS was an English mathematician, physicist, astronomer, alchemist, theologian, and author, widely recognised as one of the greatest mathematicians and physicists and among the most influential scientists of all time. He was a key figure in the philosophical revolution. known as the EnlightenmentProfoundly changed our understanding of nature with his law of universal gravitation and his laws of motion; invented calculus.is best remembered for his formulation of the three laws of motion',
        birthyear: 1643-1727,


    },
    {
        id: 17,
        name: 'Archimedes',
        image: 'https://i.ibb.co/74VJftn/Archimedes.jpg',
        birthplace: 'Greek',
        description: 'Archimedes of Syracuse was a Greek mathematician, physicist, engineer, astronomer, and inventor from the ancient city of Syracuse in Sicily. Although few details of his life are known, he is regarded as one of the leading scientists in classical antiquity.. Founded the sciences of mechanics and hydrostatics, calculated pi precisely, devised the law of exponents, created new.conceived in 287 BC, is among the greatest scientists who made breakthroughs in both theory and practice. He established the concept of .',
        birthyear: 287-212,
    },
    {
        id: 18,
        name: 'Galileo Galilei',
        image: 'https://i.ibb.co/jRbdLQD/Justus-Sustermans-Portrait-of-Galileo-Galilei-1636.jpg',
        birthplace: 'Pisa, Italy',
        description: 'The father of modern science, Galileo discovered the first moons ever known to orbit another planet and that the Milky Way is .. Born in Pisa, Italy in 1564, Galileo is called as the father of modern science because of his discoveries in astronomy and Galileo discovered the first moons ever known to orbit another planet and that the Milky Way i.Galileo discovered the first moons ever known to orbit another planet and that the Milky Way i ',
        birthyear: 1564-1642,


    },
    {
        id: 19,
        name: 'Sir Isaac Newton',
        image: 'https://i.ibb.co/2YcNVNg/gettyimages-113494597-612x612.jpg',
        birthplace: '',
        description: 'Sir Isaac Newton PRS was an English mathematician, physicist, astronomer, alchemist, theologian, and author, widely recognised as one of the greatest mathematicians and physicists and among the most influential scientists of all time. He was a key figure in the philosophical revolution. known as the EnlightenmentProfoundly changed our understanding of nature with his law of universal gravitation and his laws of motion; invented calculus.is best remembered for his formulation of the three laws of motion',
        birthyear: 1643-1727,


    },
    {
        id: 20,
        name: 'Archimedes',
        image: 'https://i.ibb.co/74VJftn/Archimedes.jpg',
        birthplace: 'Greek',
        description: 'Archimedes of Syracuse was a Greek mathematician, physicist, engineer, astronomer, and inventor from the ancient city of Syracuse in Sicily. Although few details of his life are known, he is regarded as one of the leading scientists in classical antiquity.. Founded the sciences of mechanics and hydrostatics, calculated pi precisely, devised the law of exponents, created new.conceived in 287 BC, is among the greatest scientists who made breakthroughs in both theory and practice. He established the concept of .',
        birthyear: 287-212,
    },
    {
        id: 21,
        name: 'Galileo Galilei',
        image: 'https://i.ibb.co/jRbdLQD/Justus-Sustermans-Portrait-of-Galileo-Galilei-1636.jpg',
        birthplace: 'Pisa, Italy',
        description: 'The father of modern science, Galileo discovered the first moons ever known to orbit another planet and that the Milky Way is .. Born in Pisa, Italy in 1564, Galileo is called as the father of modern science because of his discoveries in astronomy and Galileo discovered the first moons ever known to orbit another planet and that the Milky Way i.Galileo discovered the first moons ever known to orbit another planet and that the Milky Way i ',
        birthyear: 1564-1642,


    },
    {
        id: 22,
        name: 'Sir Isaac Newton',
        image: 'https://i.ibb.co/2YcNVNg/gettyimages-113494597-612x612.jpg',
        birthplace: '',
        description: 'Sir Isaac Newton PRS was an English mathematician, physicist, astronomer, alchemist, theologian, and author, widely recognised as one of the greatest mathematicians and physicists and among the most influential scientists of all time. He was a key figure in the philosophical revolution. known as the EnlightenmentProfoundly changed our understanding of nature with his law of universal gravitation and his laws of motion; invented calculus.is best remembered for his formulation of the three laws of motion',
        birthyear: 1643-1727,


    },
    {
        id: 23,
        name: 'Archimedes',
        image: 'https://i.ibb.co/74VJftn/Archimedes.jpg',
        birthplace: 'Greek',
        description: 'Archimedes of Syracuse was a Greek mathematician, physicist, engineer, astronomer, and inventor from the ancient city of Syracuse in Sicily. Although few details of his life are known, he is regarded as one of the leading scientists in classical antiquity.. Founded the sciences of mechanics and hydrostatics, calculated pi precisely, devised the law of exponents, created new.conceived in 287 BC, is among the greatest scientists who made breakthroughs in both theory and practice. He established the concept of .',
        birthyear: 287-212,
    },
    {
        id: 24,
        name: 'Galileo Galilei',
        image: 'https://i.ibb.co/jRbdLQD/Justus-Sustermans-Portrait-of-Galileo-Galilei-1636.jpg',
        birthplace: 'Pisa, Italy',
        description: 'The father of modern science, Galileo discovered the first moons ever known to orbit another planet and that the Milky Way is .. Born in Pisa, Italy in 1564, Galileo is called as the father of modern science because of his discoveries in astronomy and Galileo discovered the first moons ever known to orbit another planet and that the Milky Way i.Galileo discovered the first moons ever known to orbit another planet and that the Milky Way i ',
        birthyear: 1564-1642,


    },
    {
        id: 25,
        name: 'Sir Isaac Newton',
        image: 'https://i.ibb.co/2YcNVNg/gettyimages-113494597-612x612.jpg',
        birthplace: '',
        description: 'Sir Isaac Newton PRS was an English mathematician, physicist, astronomer, alchemist, theologian, and author, widely recognised as one of the greatest mathematicians and physicists and among the most influential scientists of all time. He was a key figure in the philosophical revolution. known as the EnlightenmentProfoundly changed our understanding of nature with his law of universal gravitation and his laws of motion; invented calculus.is best remembered for his formulation of the three laws of motion',
        birthyear: 1643-1727,


    },
    {
        id: 26,
        name: 'Archimedes',
        image: 'https://i.ibb.co/74VJftn/Archimedes.jpg',
        birthplace: 'Greek',
        description: 'Archimedes of Syracuse was a Greek mathematician, physicist, engineer, astronomer, and inventor from the ancient city of Syracuse in Sicily. Although few details of his life are known, he is regarded as one of the leading scientists in classical antiquity.. Founded the sciences of mechanics and hydrostatics, calculated pi precisely, devised the law of exponents, created new.conceived in 287 BC, is among the greatest scientists who made breakthroughs in both theory and practice. He established the concept of .',
        birthyear: 287-212,
    },
]