export const poets = [
    {
        id: 1,
        name: "Rabindranath Tagore",
        image: "https://i.ibb.co/mCGXSQR/1024px-Rabindranath-Tagore-5c50f0a946e0fb0001c0dd28.jpg",
        birthplace: "Jorasanko Thakurbari, Kolkata, India",
        description: "Rabindranath Tagore FRAS was a Bengali polymath who worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1861,
        booksnumber: 230,
        famouspoem: "Gitanjali",
    },
    {
        id: 2,
        name: "Kazi Nazrul Islam",
        image: "https://i.ibb.co/rfVKfYy/Islam-Kazi-Nazrul.jpg",
        birthplace: "Churulia, India",
        description: "Kazi Nazrul Islam was a Bengali poet, writer, musician, and is the national poet of Bangladesh. Nazrul is regarded as one of the greatest poets in Bengali literature.worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1899,
        booksnumber: 161,
        famouspoem: "Bidrohi",

    },
    {
        id: 3,
        name: "Michael Madhusudan Dutt",
        image: "https://i.ibb.co/gF4tT48/4ada4-f093b6c112-long.jpg",
        birthplace: "Jessore District",
        description: "Michael Madhusudan Dutt was a Bengali poet and playwright. He is considered one of the pioneers of Bengali literature.worked as a poet, writer, playwright, composer, philosopher, social reformer and painter. He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1824,
        booksnumber: 114,
        famouspoem: "Kapotakkho Nod",
    },
    {
        id: 4,
        name: "Sufia Kamal",
        image: "https://i.ibb.co/8dWLmLH/images.jpg",
        birthplace: "Tahare Pore Mone",
        description: "Begum Sufia Kamal was a Bangladeshi poet, feminist leader, and political activist. She took part in the Bengali nationalist movement of the 1950s and civil society leader in independent Bangladesh. She led feminist activism and was a president of Bangladesh Mahila Parishad.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1911,
        booksnumber: 95,
        famouspoem: "Kapotakkho Nod",
    },
    {
        id: 5,
        name: "Edgar Allen Poe",
        image: "https://i.ibb.co/Gvs8JZy/Edgar-Allan-Poe-1.webp",
        birthplace: "Boston",
        description: "Edgar Allan Poe was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1809,
        booksnumber: 33,
        famouspoem: "The Raven",
    },
    {
        id: 6,
        name: "William Shakespeare",
        image: "https://i.ibb.co/82ygx6Y/shakespeare.jpg",
        birthplace: "Stratford-upon-Avon, England",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1564,
        booksnumber: 154,
        famouspoem: "Sonnet XVIII",
    },
    {
        id: 7,
        name: "Maya Angelou",
        image: "https://i.ibb.co/ZY83RwR/3503.jpg",
        birthplace: "St. Louis",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1928,
        booksnumber: 72,
        famouspoem: "On the Pulse of Morning",
    },
    {
        id: 8,
        name: "Shel Silverstein",
        image: "https://i.ibb.co/w0w6Kzz/Shel-Silverstein.webp",
        birthplace: "Chicago",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1930,
        booksnumber: 84,
        famouspoem: "Where the Sidewalk Ends",
    },
    {
        id: 9,
        name: "Robert Frost",
        image: "https://i.ibb.co/0KH59Mf/Robert-Frost-1910s.jpg",
        birthplace: "San Francisco",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1874,
        booksnumber: 92,
        famouspoem: "The Road Not Taken",
    },
    {
        id: 10,
        image: "https://i.ibb.co/HNjfq8D/neruda-13228-portrait-medium.jpg",
        name: "Pablo Neruda",
        birthplace: "Parral, Chile",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1904,
        booksnumber: 50,
        famouspoem: "I Do Not Love You Except Because I Love You",
    },
    {
        id: 11,
        name: "E. E. Cummings",
        image: "https://i.ibb.co/JBZb95t/140303-r24673.webp",
        birthplace: "Cambridge, Massachusetts",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1894,
        booksnumber: 78,
        famouspoem: "i carry your heart with me",
    },
    {
        id: 12,
        name: "John Keats",
        image: "https://i.ibb.co/vdDX057/images-1.jpg",
        birthplace: "London",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1795,
        booksnumber: 121,
        famouspoem: "A Thing of Beauty",
    },
    {
        id: 13,
        name: "Jalal al-Din Rumi",
        image: "https://i.ibb.co/MhxpG2K/images-2.jpg",
        birthplace: "Khorasan present-day Afghanistan",
        description: "William Shakespeare was an American writer, poet, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States, and of American literature.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.He reshaped Bengali literature and music as well as Indian art with Contextual Modernism in the late 19th and early 20th centuries.",
        birthyear: 1207,
        booksnumber: 147,
        famouspoem: "Masnavi-ye Ma’navi",
    }
]